Fix xfstests Test
Due recent change test is failing as if device is nvdimm
self.log_test  and self.log_scratch complain as undefined
in test due to that is broken this patch fix this issue

before fix

(1/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_1-2238: ERROR: 'Xfstests' object has no attribute 'log_test' (3.69 s)
(2/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_2-1eeb: ERROR: 'Xfstests' object has no attribute 'log_test' (3.62 s)
(3/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_3-5841: ERROR: 'Xfstests' object has no attribute 'log_test' (3.03 s)
(4/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_4-3d83

after Fix:

system:/home/chandan/avocado-misc-tests/fs # avocado run xfstests.py -m xfstests.py.data/xfstests.yaml
/usr/lib/python3.6/site-packages/avocado_framework-76.0-py3.6.egg/avocado/plugins/run.py:287: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  FutureWarning)
Error running method "pre_tests" of plugin "fetchasset": 'Attribute' object has no attribute 'id'
JOB ID     : cff891abd81d65802c6b3378fff838829f0ac71f
JOB LOG    : /root/avocado/job-results/job-2020-03-13T10.02-cff891a/job.log
 (1/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_1-2238: FAIL: One or more tests failed. Please check the logs. (29.61 s)
 (2/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_2-1eeb: FAIL: One or more tests failed. Please check the logs. (6.50 s)
 (3/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_3-5841: FAIL: One or more tests failed. Please check the logs. (6.38 s)
 (4/4) xfstests.py:Xfstests.test;disk_type-fs_xfs_4-3d83: FAIL: One or more tests failed. Please check the logs. (6.14 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Reported-by:   Chandan Rajendra <chandanrlinux@gmail.com>
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>