ipistorm test case fails to run with following error: DBLIPIStrom.test: ERROR: 'module' object has no attribute 'get_family'
Use distro.detect().arch statement to check for ppc architecture.
Additionally use online_cpus_count() method instead of online_count().

While at it fix pycodestyle warning against line 91.

Signed-off-by: Sachin Sant sachinp@linux.vnet.ibm.com