Change default parameter values for standalone test execution
Patch fixes the following error, as default value is missing when
test is executed without any inputs.
ValueError: invalid literal for int() with base 10: ''
This patch fixes it.

Signed-off-by: Harish <harish@linux.vnet.ibm.com>