If cpupower utility is not installed the CpupowerMonitor test fails with following error:
ERROR: 'CpupowerMonitor' object has no attribute 'states_list'

Make sure cpupower utility is installed.
As pointed out remove the typo fix since it is included in patch 2.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>