ERROR: Failed to fetch stress-1.0.4.tar.gz
The stress-1.0.4.tar.gz link has been moved to another folder
so pointing the URL to the right folder

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>