fix arg problem when ping fails
Due to args not intialize before take connections, the test
gives wrong message when ping fails, so this change will
fix Error: 'Ethtool' object has no attribute 'args'

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>