Fix ERROR : 'MemStress' object has no attribute 'blocks_hotpluggable'
Running memhotplug.py test is causing the error:

(1/4) tests/avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_loop: STARTED
(1/4) tests/avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_loop:
ERROR: 'MemStress' object has no attribute 'blocks_hotpluggable' (2.51 s)

Issue: Old link of stress tar is no longer valid

Fixes:
1. Add new link of stress tar
2. Add the stress tar as a parameter that can be configured from yaml
3. Make the necessary changes to run the new stress tar

Signed-off-by: Geetika <geetika@linux.ibm.com>