kernel/willitscale: Numa check and package dependency fix
will-it-scale test fails to compile code on RHEL with
ERROR: Command 'make' failed.\nstdout: b'cc
The failure is due to missing check for RHEL as a distribution release
name and hence misses to install hwloc-devel package. Add the check so
all the required dependent packages are installed.

Additionally the will-it-scale tool does not require multiple NUMA nodes
to function. The tool uses hwloc to detect and distribute tasks across
CPU cores/PUs,not NUMA nodes specifically
The NUMA node check was preventing the test from running on valid
single-node systems where the tool would work correctly. This patch
remove the numa check.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>