sosreport.py:AttributeError: 'dict' object has no attribute 'iteritems'
dict.iteritems() was removed in python3,instead using dict.items()
So changed the script in order to get rid of that error

Signed-off-by: shirisha Ganta <shiganta@in.ibm.com>