perf/perf_sdt_probe: refine parsing logic for locating libpthread and libc
On recent SLES distro test fails with below error due to issues
locating libpthread and libc.
ERROR: Unable to remove 1062 libs found in cache `/etc/ld.so.cache’

On older distros, the path were identified as follows:
libpthread.so.0 (libc6,64bit, OS ABI: Linux 3.10.0) => /lib64/libpthread.so.0
libc.so.6 (libc6,64bit, OS ABI: Linux 3.10.0) => /lib64/libc.so.6

On current distro, the format changed to:
libpthread.so.0 (libc6,64bit) => /lib64/libpthread.so.0
libc.so.6 (libc6,64bit) => /lib64/libc.so.6

To address this, the parsing logic is updated to correctly identify
the paths in both cases.

Signed-off-by: Disha Goel <disgoel@linux.ibm.com>