memory/thp_defrag: Fix syntax error
THP defrag test fails with following syntax error:
 self.device.mount(mountpoint=self.mem_path, fstype, mnt_check=False)
                                            ^
 SyntaxError: positional argument follows keyword argument

commit 3237c43d2168 changed the keyword arg to positional. This
patch reverts that change.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>