Fix compiling error Valgrind test (ppc64el)
There is a compiling error when running valgrind testcase on ppc64el.

m_debuglog.c: In function ‘local_sys_write_stderr’:
m_debuglog.c:203:4: error: PIC register clobbered by ‘r2’ in ‘asm’
    __asm__ volatile (
    ^~~~~~~
m_debuglog.c: In function ‘vgPlain_debugLog’:
m_debuglog.c:228:4: error: PIC register clobbered by ‘r2’ in ‘asm’
    __asm__ volatile (
    ^~~~~~~

In the upstream version (v3.13) it's already fixed. So, by just using
the upstream version instead of v3.12, this error does not happen.

Signed-off-by: Rodrigo R. Galvao <rosattig@br.ibm.com>