Fix: Add new package for kernel selftest
New test introduced under vm directory of selftest requires
libhugetlbfs devel packages. Without that building fails

[stderr] hmm-tests.c:24:23: fatal error: hugetlbfs.h: No such file or directory
[stderr]  #include <hugetlbfs.h>
[stderr]                        ^
[stderr] compilation terminated.

Signed-off-by: Harish <harish@linux.ibm.com>