Fix runtime syntax errors
cpupower testcase fails with following runtime syntax error
SyntaxError: EOL while scanning string literal

Fix the lines causing these errors.

Signed-off-by: Sachin Sant <sachinp@linux.vnet.ibm.com>