Fix compilation issue in recent ubuntu distro
added libgdbm-compat-dev as required package

LOG:

dbtest.c:197:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  dbm = dbm_open(filename, O_RDONLY, 0);
      ^
dbtest.c: In function 'DoDbmLookup':
dbtest.c:205:2: error: unknown type name 'datum'
  datum key, content;
  ^~~~~
dbtest.c:207:8: error: 'dbp' undeclared (first use in this function); did you mean 'dbm'?
  myDB *dbp;
        ^~~
        dbm
dbtest.c:213:6: error: request for member 'dptr' in something not a structure or union
   key.dptr = (char *)(KeyArray+j);
      ^
dbtest.c:214:6: error: request for member 'dsize' in something not a structure or union
   key.dsize = sizeof(KeyArray[0]);
      ^
dbtest.c:221:13: warning: implicit declaration of function 'dbm_fetch' [-Wimplicit-function-declaration]
   content = dbm_fetch(dbm, key);
             ^~~~~~~~~
dbtest.c:222:16: error: expected expression before ')' token
   dbp = (myDB *)content.dptr;
                ^
dbtest.c:223:16: error: request for member 'dptr' in something not a structure or union
   if ( !content.dptr ) {
                ^
dbtest.c:224:8: warning: implicit declaration of function 'dbm_error'; did you mean 'strerror'? [-Wimplicit-function-declaration]
    n = dbm_error(dbm);
        ^~~~~~~~~
        strerror
dbtest.c:243:14: error: request for member 'dsize' in something not a structure or union
   if (content.dsize == 0) {
              ^
dbtest.c:246:37: error: request for member 'dsize' in something not a structure or union
    DoSysError("\ndbm_fetch", content.dsize);
                                     ^
dbtest.c:259:6: error: request for member 'dptr' in something not a structure or union
   key.dptr = (char *)(KeyArray+n);
      ^
dbtest.c:260:6: error: request for member 'dsize' in something not a structure or union
   key.dsize = sizeof(KeyArray[0]);
      ^
dbtest.c:266:16: error: expected expression before ')' token
   dbp = (myDB *)content.dptr;
                ^
dbtest.c:267:16: error: request for member 'dptr' in something not a structure or union
   if ( !content.dptr ) {
                ^
dbtest.c:286:14: error: request for member 'dsize' in something not a structure or union
   if (content.dsize == 0)
              ^
dbtest.c:287:37: error: request for member 'dsize' in something not a structure or union
    DoSysError("\ndbm_fetch", content.dsize);
                                     ^
dbtest.c:205:13: warning: variable 'content' set but not used [-Wunused-but-set-variable]
  datum key, content;
             ^~~~~~~
dbtest.c: At top level:
dbtest.c:321:16: error: expected declaration specifiers or '...' before 'myDB'
 int creatDbRec(myDB *dbp)
                ^~~~
dbtest.c: In function 'InitDbmLookup':
dbtest.c:174:3: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   write(2, NULL, 0);
   ^~~~~~~~~~~~~~~~~

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>