fix: add unicode param when file is read as string
The /tmp/tmpfile is read as string and not converted to unicode on python2.7
so test is failing with this error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal

fixed to decode from str to unicode(UTF-8)

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>