Fix HTX test case as RHEL9 onwards test does not support upstream version of HTX
relvent error log

make[1]: Entering directory '/home/HTX-master/bin'
making dir - /home/HTX-master//install/ppc64le//usr/lpp/htx//bin/
/bin/mkdir -p /home/HTX-master//install/ppc64le//usr/lpp/htx//bin/
make -C hxssup
make[2]: Entering directory '/home/HTX-master/bin/hxssup'
cc  -L/home/HTX-master//export/ppc64le//lib// nf.o start_msg.o shell.o screens.o mmenu.o misc.o hxssup.o help.o search_win.o hang_monitor.o get_dispid.o erpt.o edit.o disp_dst.o build_ipc.o T_device.o R_device.o IT_device.o COE_devic.o A_device.o ART_device.o AH_system.o AH_device.o random_ahd.o equaliser.o hotplug.o -Wl,--start-group -lrt -lhtx64 -lpthread -lc -lcfgc64 -lncurses -ltinfo -lc -Wl,--end-group -o hxssup
/usr/bin/ld: edit.o:(.bss+0x0): multiple definition of `editor_PID'; hxssup.o:(.bss+0x31a4): first defined here
/usr/bin/ld: equaliser.o:(.bss+0x28): multiple definition of `equaliser_debug_flag'; build_ipc.o:(.bss+0x100c): first defined here
/usr/bin/ld: hotplug.o:(.bss+0x0): multiple definition of `rwlattr'; equaliser.o:(.bss+0x0): first defined here
/usr/bin/ld: /home/HTX-master//export/ppc64le//lib///libhtx64.a(hxfupdate.o):(.bss+0x2050): multiple definition of `ecg_info'; build_ipc.o:(.bss+0x1000): first defined here
/usr/bin/ld: /home/HTX-master//export/ppc64le//lib///libhtx64.a(htxsyscfg.o):(.bss+0x120): multiple definition of `rwlattr'; equaliser.o:(.bss+0x0): first defined here
/usr/bin/ld: A_device.o: in function `A_device':
A_device.c:(.text+0x584): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: R_device.o: in function `exec_HE_script':
R_device.c:(.text+0x688): warning: the use of `tempnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:46: all] Error 1
make[2]: Leaving directory '/home/HTX-master/bin/hxssup'
make[1]: *** [Makefile:33: hxssup] Error 2
make[1]: Leaving directory '/home/HTX-master/bin'
make: *** [Makefile:25: bin] Error 2

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>