fs/xfstests: Move package installation after variable initialization
In case a certain package install operation fails, the test fails
with a completely different message

ERROR: 'Xfstests' object has no attribute 'scratch_mnt' (15.37 s)

The package install function is called before various variable
initialization. In case of install fail, test errors out due
to usage of uniniitalized variables in teardown.

Move the package install function call post variable initialization

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>